### ISSUE TITLE
Politica de privacidad

### ISSUE THREAD

**Issue by rurigk** [AlexAzumi/az-player#6]
Necesitas informar al usuario que el programa incluye un monitor de actividad (sentry) y el fin con el que se usaran los datos recopilados

En muchos paises se requiere por ley y deberias agregar una forma de desactivar la recopilacion de datos

Y no dejar usar la aplicacion si no se ha aceptado la politica de privacidad

**Comment by AlexAzumi** [comment]
No había tomado en cuenta la parte legal de la recopilación de datos, pero estás en lo correcto.
Para la próxima versión se mostrará un cuadro de información sobre la recopilación de datos e incluiré una forma de desactivarlo.

Muchas gracias por la información @rurigk
